import './global.css';
import Providers from './providers';
import { Poppins } from 'next/font/google';

export const metadata = {
  title: 'NextBuy Seller',
  description: 'Generated by create-nx-workspace',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-white font-sans ${poppins.variable} font-poppins`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
